// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "shortcutMode": string;
      "resultsLimit": number;
      "aiEnabled": boolean;
      "aiProvider": string;
      "aiApiKey": string;
      "aiBaseUrl": string;
      "aiModel": string;
    };
  }
}
