// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "shortcutMode": string;
      "commandShortcutEnabled": boolean;
      "searchShortcut": string;
      "commandShortcut": string;
      "guideShortcut": string;
      "resultsLimit": number;
    };
  }
}
